#pragma once

class GolemClimb
{
public:
    GolemClimb(char const*);
    init(al::ActorInitInfo const&);
    attackSensor(al::HitSensor*, al::HitSensor*);
    appear();
    kill();
    control();
    receiveMsg(al::SensorMsg const*, al::HitSensor*, al::HitSensor*);
    startDown();
    startDamage();
    exeReady();
    exeMove();
    endMove();
    exeDamage();
    exeDownStart();
    endDownStart();
    exeDown();
    endDown();
    exeDownShout();
    exeDownRecover();
    endDownRecover();
    exeDownBreak();
    exeStandBreak();
    exeRun();
    exeShout();
    exeLegRecoverFull();
    exeLegRecoverHalf();
    exeTest();
    exeDemoBattleStart();
    exeDemoBattleEnd();
    exeDemoSimpleFade();
    exeDemoSimpleMain();
    exeBattleStart();
    updateLookAt();
    isFirstDemo() const;
    isEnableSkipDemo() const;
    skipDemo();
    updateOnlyDemoGrapics();
    throwReflectBomb();
    throwTsukkun();
    startDemo();
    endDemo();
    startShout();
    endShout();
    replaceDemoPlayer();
    getShoutPos(sead::Vector3<float>*) const;
    stampFoot(sead::Vector3<float> const&, sead::Quat<float> const&);
    showDamageArea();
    hideDamageArea();
    setDamageAreaPose(sead::Matrix34<float> const&);
    throwSearchBomb();
    updatePushSensor();
    endPushSensor();
    tryNextPushSensor() const;
    getActor();
    getSkeleton();
    getFootRootL() const;
    getFootRootR() const;
    getThrustPointL() const;
    getThrustPointR() const;
    getWeakPoint(int) const;
    isPrepareShout() const;
    getDemoSkip();
    isInFootL();
    isInFootR();
    isMoon();
};
