#pragma once

namespace al { namespace al {

createActorFunction<AchievementNpc>(char const*);
createActorFunction<AirBubble>(char const*);
createActorFunction<AirBubbleGenerator>(char const*);
createActorFunction<AirCurrent>(char const*);
createActorFunction<al::AllDeadWatcher>(char const*);
createActorFunction<AllDeadWatcherWithShine>(char const*);
createActorFunction<AmiiboHelpNpc>(char const*);
createActorFunction<AmiiboNpc>(char const*);
createActorFunction<AnagramAlphabet>(char const*);
createActorFunction<Barrel2D>(char const*);
createActorFunction<BarrelGenerator2D>(char const*);
createActorFunction<BarrierField>(char const*);
createActorFunction<BazookaElectric>(char const*);
createActorFunction<BendLeafTree>(char const*);
createActorFunction<al::BgmPlayObj>(char const*);
createActorFunction<Bird>(char const*);
createActorFunction<BirdCarryMeat>(char const*);
createActorFunction<BirdPlayerGlideCtrl>(char const*);
createActorFunction<BlockBrick>(char const*);
createActorFunction<BlockBrick2D>(char const*);
createActorFunction<BlockBrickBig2D>(char const*);
createActorFunction<BlockEmpty>(char const*);
createActorFunction<BlockEmpty2D>(char const*);
createActorFunction<BlockHard>(char const*);
createActorFunction<BlockQuestion>(char const*);
createActorFunction<BlockQuestion2D>(char const*);
createActorFunction<BlockTransparent>(char const*);
createActorFunction<BlockTransparent2D>(char const*);
createActorFunction<BlowObj>(char const*);
createActorFunction<BombTail>(char const*);
createActorFunction<BossForest>(char const*);
createActorFunction<BossForestBlock>(char const*);
createActorFunction<BossForestWander>(char const*);
createActorFunction<BossKnuckle>(char const*);
createActorFunction<BossKnuckleCounterGround>(char const*);
createActorFunction<BossKnuckleFix>(char const*);
createActorFunction<BossMagma>(char const*);
createActorFunction<BossRaid>(char const*);
createActorFunction<BossRaidNpc>(char const*);
createActorFunction<BossRaidRivet>(char const*);
createActorFunction<BreakablePole>(char const*);
createActorFunction<Breeda>(char const*);
createActorFunction<Bubble>(char const*);
createActorFunction<Bubble2D>(char const*);
createActorFunction<BubbleLauncher>(char const*);
createActorFunction<Bull>(char const*);
createActorFunction<Byugo>(char const*);
createActorFunction<Cactus>(char const*);
createActorFunction<CactusMini>(char const*);
createActorFunction<CageShineWatcher>(char const*);
createActorFunction<CageSwitch>(char const*);
createActorFunction<BreakMapParts>(char const*);
createActorFunction<CameraDemoGateMapParts>(char const*);
createActorFunction<CameraDemoKeyMoveMapParts>(char const*);
createActorFunction<al::CameraRailHolder>(char const*);
createActorFunction<CameraSub>(char const*);
createActorFunction<al::CameraWatchPoint>(char const*);
createActorFunction<Candlestand>(char const*);
createActorFunction<CandlestandInitializer>(char const*);
createActorFunction<CandlestandBgmDirector>(char const*);
createActorFunction<CandlestandSaveWatcher>(char const*);
createActorFunction<CandlestandWatcher>(char const*);
createActorFunction<CapAccelerator>(char const*);
createActorFunction<CapAppearMapParts>(char const*);
createActorFunction<CapBeamer>(char const*);
createActorFunction<CapBomb>(char const*);
createActorFunction<CapCatapult>(char const*);
createActorFunction<CapFlower>(char const*);
createActorFunction<CapFlowerGroup>(char const*);
createActorFunction<CapHanger>(char const*);
createActorFunction<CapMessageAfterInformation>(char const*);
createActorFunction<CapRack>(char const*);
createActorFunction<CapRailMover>(char const*);
createActorFunction<CapSlotBase>(char const*);
createActorFunction<CapSwitch>(char const*);
createActorFunction<CapSwitchTimer>(char const*);
createActorFunction<CapThrower>(char const*);
createActorFunction<CapTrampoline>(char const*);
createActorFunction<Car>(char const*);
createActorFunction<CarWatcher>(char const*);
createActorFunction<CardboardBox>(char const*);
createActorFunction<CatchBomb>(char const*);
createActorFunction<Chair>(char const*);
createActorFunction<CheckpointFlag>(char const*);
createActorFunction<ChorobonHolder>(char const*);
createActorFunction<ChurchDoor>(char const*);
createActorFunction<CityBuilding>(char const*);
createActorFunction<CityStreetlight>(char const*);
createActorFunction<CityWorldSign>(char const*);
createActorFunction<CityWorldUndergroundMachine>(char const*);
createActorFunction<CitySign>(char const*);
createActorFunction<CitySignal>(char const*);
createActorFunction<ReactionObject>(char const*);
createActorFunction<Closet>(char const*);
createActorFunction<CloudStep>(char const*);
createActorFunction<CollapseSandHill>(char const*);
createActorFunction<CollectAnimalWatcher>(char const*);
createActorFunction<CollectBgmSpeaker>(char const*);
createActorFunction<CollectionList>(char const*);
createActorFunction<Coin>(char const*);
createActorFunction<Coin2D>(char const*);
createActorFunction<Coin2DCityDirector>(char const*);
createActorFunction<CoinBlow>(char const*);
createActorFunction<CoinChameleon>(char const*);
createActorFunction<CoinCirclePlacement>(char const*);
createActorFunction<CoinCollect>(char const*);
createActorFunction<CoinCollectHintObj>(char const*);
createActorFunction<CoinCollect2D>(char const*);
createActorFunction<CoinLead>(char const*);
createActorFunction<CoinRail>(char const*);
createActorFunction<CoinRing>(char const*);
createActorFunction<CoinStackGroup>(char const*);
createActorFunction<CrystalBreakable>(char const*);
createActorFunction<DamageBallGenerator>(char const*);
createActorFunction<DelaySwitch>(char const*);
createActorFunction<DemoActorCapManHero>(char const*);
createActorFunction<DemoActorCapManHeroine>(char const*);
createActorFunction<DemoActorKoopaShip>(char const*);
createActorFunction<DemoActorHack>(char const*);
createActorFunction<DemoActorPeach>(char const*);
createActorFunction<DemoActorShineTower>(char const*);
createActorFunction<al::RippleFixMapParts>(char const*);
createActorFunction<DemoChangeEffectObj>(char const*);
createActorFunction<DemoWorldMoveHomeBackGround>(char const*);
createActorFunction<DemoPeachWedding>(char const*);
createActorFunction<DemoPlayer>(char const*);
createActorFunction<DemoPlayerCap>(char const*);
createActorFunction<DigPoint>(char const*);
createActorFunction<al::FixMapParts>(char const*);
createActorFunction<Dokan>(char const*);
createActorFunction<DokanKoopa>(char const*);
createActorFunction<DokanMaze>(char const*);
createActorFunction<DokanMazeDirector>(char const*);
createActorFunction<DokanStageChange>(char const*);
createActorFunction<DonkeyKong2D>(char const*);
createActorFunction<Donsuke>(char const*);
createActorFunction<Doshi>(char const*);
createActorFunction<DoorAreaChange>(char const*);
createActorFunction<DoorAreaChangeCap>(char const*);
createActorFunction<DoorCity>(char const*);
createActorFunction<DoorSnow>(char const*);
createActorFunction<DoorWarp>(char const*);
createActorFunction<DoorWarpStageChange>(char const*);
createActorFunction<EchoBlockMapParts>(char const*);
createActorFunction<al::EffectObj>(char const*);
createActorFunction<EffectObjAlpha>(char const*);
createActorFunction<al::EffectObjCameraEmit>(char const*);
createActorFunction<al::EffectObjFollowCamera>(char const*);
createActorFunction<al::EffectObjFollowCameraLimit>(char const*);
createActorFunction<al::EffectObjInterval>(char const*);
createActorFunction<EffectObjNpcManFar>(char const*);
createActorFunction<EffectObjQualityChange>(char const*);
createActorFunction<ElectricWire>(char const*);
createActorFunction<ElectricWireKoopa>(char const*);
createActorFunction<al::EntranceCameraStartObj>(char const*);
createActorFunction<EventKeyMoveCameraObjNoDemo>(char const*);
createActorFunction<EventKeyMoveCameraObjWithDemo>(char const*);
createActorFunction<FigureWalkingNpc>(char const*);
createActorFunction<FireBlower>(char const*);
createActorFunction<FireBros>(char const*);
createActorFunction<FireSwitch>(char const*);
createActorFunction<FireHydrant>(char const*);
createActorFunction<FireDrum2D>(char const*);
createActorFunction<FishingFish>(char const*);
createActorFunction<FixMapParts2D>(char const*);
createActorFunction<FixMapPartsAppearKillAsync>(char const*);
createActorFunction<FixMapPartsBgmChangeAction>(char const*);
createActorFunction<FixMapPartsCapHanger>(char const*);
createActorFunction<FixMapPartsDitherAppear>(char const*);
createActorFunction<FixMapPartsForceSafetyPoint>(char const*);
createActorFunction<FixMapPartsFukankunZoomCapMessage>(char const*);
createActorFunction<FixMapPartsScenarioAction>(char const*);
createActorFunction<FlyObject>(char const*);
createActorFunction<ForestManSeed>(char const*);
createActorFunction<al::FogRequester>(char const*);
createActorFunction<FrailBox>(char const*);
createActorFunction<Frog>(char const*);
createActorFunction<Fukankun>(char const*);
createActorFunction<FukankunZoomCapMessageSun>(char const*);
createActorFunction<FukuwaraiWatcher>(char const*);
createActorFunction<ForestWorldEnergyStand>(char const*);
createActorFunction<ForestWorldFlowerCtrl>(char const*);
createActorFunction<GabuZou>(char const*);
createActorFunction<GabuZouGroup>(char const*);
createActorFunction<Gamane>(char const*);
createActorFunction<GiantWanderBoss>(char const*);
createActorFunction<GoalMark>(char const*);
createActorFunction<GolemClimb>(char const*);
createActorFunction<Gotogoton>(char const*);
createActorFunction<GotogotonGoal>(char const*);
createActorFunction<ProjectGraphicsObjShadowMaskCube>(char const*);
createActorFunction<al::GraphicsObjShadowMaskSphere>(char const*);
createActorFunction<GrowerBug>(char const*);
createActorFunction<GrowerWorm>(char const*);
createActorFunction<GrowFlowerCoin>(char const*);
createActorFunction<GrowFlowerWatcher>(char const*);
createActorFunction<GrowPlantGrowPlace>(char const*);
createActorFunction<GrowPlantSeed>(char const*);
createActorFunction<GrowPlantStartStage>(char const*);
createActorFunction<GrowPlantWatcher>(char const*);
createActorFunction<GunetterSpin>(char const*);
createActorFunction<Gunetter>(char const*);
createActorFunction<HackCar>(char const*);
createActorFunction<HackFork>(char const*);
createActorFunction<HammerBros>(char const*);
createActorFunction<HammerBros2D>(char const*);
createActorFunction<HelpNpc>(char const*);
createActorFunction<HintNpc>(char const*);
createActorFunction<HintPhoto>(char const*);
createActorFunction<HintRouteGuidePoint>(char const*);
createActorFunction<HipDropSwitch>(char const*);
createActorFunction<HipDropSwitchTimer>(char const*);
createActorFunction<HipDropTile>(char const*);
createActorFunction<HipDropMoveLift>(char const*);
createActorFunction<HipDropRepairParts>(char const*);
createActorFunction<HipDropTransformPartsWatcher>(char const*);
createActorFunction<HomeBed>(char const*);
createActorFunction<HomeChair>(char const*);
createActorFunction<HomeInside>(char const*);
createActorFunction<HomeShip>(char const*);
createActorFunction<Hosui>(char const*);
createActorFunction<IcicleFall>(char const*);
createActorFunction<Imomu>(char const*);
createActorFunction<IndicatorDirector>(char const*);
createActorFunction<Jango>(char const*);
createActorFunction<Joku>(char const*);
createActorFunction<JugemFishing>(char const*);
createActorFunction<JumpingRopeNpc>(char const*);
createActorFunction<Kakku>(char const*);
createActorFunction<KaronWing>(char const*);
createActorFunction<al::KeyMoveCameraObj>(char const*);
createActorFunction<KickStone>(char const*);
createActorFunction<KillerLauncher>(char const*);
createActorFunction<KillerLauncherDot>(char const*);
createActorFunction<KinokoUfo>(char const*);
createActorFunction<Koopa>(char const*);
createActorFunction<KoopaCapPlayer>(char const*);
createActorFunction<KoopaChurch>(char const*);
createActorFunction<KoopaLv1>(char const*);
createActorFunction<KoopaShip>(char const*);
createActorFunction<Kuribo2D>(char const*);
createActorFunction<KuriboGenerator2D>(char const*);
createActorFunction<KuriboGirl>(char const*);
createActorFunction<KuriboHack>(char const*);
createActorFunction<KuriboMini>(char const*);
createActorFunction<KuriboTowerSwitch>(char const*);
createActorFunction<KuriboWing>(char const*);
createActorFunction<LavaFryingPan>(char const*);
createActorFunction<LavaStewVeget>(char const*);
createActorFunction<LavaPan>(char const*);
createActorFunction<LavaWave>(char const*);
createActorFunction<LifeMaxUpItem>(char const*);
createActorFunction<LifeMaxUpItem2D>(char const*);
createActorFunction<LifeUpItem>(char const*);
createActorFunction<LifeUpItem2D>(char const*);
createActorFunction<al::LightningController>(char const*);
createActorFunction<LongGenerator>(char const*);
createActorFunction<MarchingCubeBlock>(char const*);
createActorFunction<MapPartsRoulette>(char const*);
createActorFunction<Megane>(char const*);
createActorFunction<MeganeLiftExLift>(char const*);
createActorFunction<MeganeKeyMoveMapParts>(char const*);
createActorFunction<MeganeMapParts>(char const*);
createActorFunction<Mirror>(char const*);
createActorFunction<MoonBasementBreakParts>(char const*);
createActorFunction<MoonBasementClimaxWatcher>(char const*);
createActorFunction<MoonBasementMeteorPointObj>(char const*);
createActorFunction<MoonBasementFinalGate>(char const*);
createActorFunction<MoonBasementFallObjDecoration>(char const*);
createActorFunction<MoonBasementFloor>(char const*);
createActorFunction<MoonBasementGate>(char const*);
createActorFunction<MoonBasementMeteorAreaObj>(char const*);
createActorFunction<MoonBasementPillar>(char const*);
createActorFunction<MoonBasementRock>(char const*);
createActorFunction<MoonBasementSlideObj>(char const*);
createActorFunction<MoonRock>(char const*);
createActorFunction<MoonWorldBell>(char const*);
createActorFunction<MoonWorldCaptureParadeLift>(char const*);
createActorFunction<Mofumofu>(char const*);
createActorFunction<MofumofuScrap>(char const*);
createActorFunction<Motorcycle>(char const*);
createActorFunction<MotorcycleParkingLot>(char const*);
createActorFunction<MoveHomeNpc>(char const*);
createActorFunction<MoviePlayerMapParts>(char const*);
createActorFunction<MultiGateKeeperBonfire>(char const*);
createActorFunction<MultiGateKeeperWatcher>(char const*);
createActorFunction<Mummy>(char const*);
createActorFunction<MummyGenerator>(char const*);
createActorFunction<NeedleTrap>(char const*);
createActorFunction<Nokonoko2D>(char const*);
createActorFunction<NoteObj>(char const*);
createActorFunction<NoteObj2D>(char const*);
createActorFunction<NoteObjDirector>(char const*);
createActorFunction<Objex>(char const*);
createActorFunction<al::OccludedEffectRequester>(char const*);
createActorFunction<OceanWaveActor>(char const*);
createActorFunction<al::OneMeshFixMapParts>(char const*);
createActorFunction<OpeningStageStartDemo>(char const*);
createActorFunction<PackunFire>(char const*);
createActorFunction<PadRumblePoint>(char const*);
createActorFunction<PaintObj>(char const*);
createActorFunction<PaulineAtCeremony>(char const*);
createActorFunction<PaulineAudience>(char const*);
createActorFunction<PeachCastleCap>(char const*);
createActorFunction<PeachWorldGate>(char const*);
createActorFunction<PeachWorldMoatWater>(char const*);
createActorFunction<PeachWorldTree>(char const*);
createActorFunction<Pecho>(char const*);
createActorFunction<Pen>(char const*);
createActorFunction<PictureStageChange>(char const*);
createActorFunction<PillarKeyMoveParts>(char const*);
createActorFunction<PillarSwitchOpenMapParts>(char const*);
createActorFunction<PlayerMotionObserver>(char const*);
createActorFunction<PlayerStartObj>(char const*);
createActorFunction<PlayerSubjectiveWatchCheckObj>(char const*);
createActorFunction<PlayGuideBoard>(char const*);
createActorFunction<PlayRecorder>(char const*);
createActorFunction<PochiHintPhoto>(char const*);
createActorFunction<Poetter>(char const*);
createActorFunction<PoleClimbParts>(char const*);
createActorFunction<PoleGrabCeil>(char const*);
createActorFunction<PopnGenerator>(char const*);
createActorFunction<ReactionObjectPoster>(char const*);
createActorFunction<ReactionObjectSkyRhythm>(char const*);
createActorFunction<PosterWatcher>(char const*);
createActorFunction<PrePassCausticsLight>(char const*);
createActorFunction<al::PrePassLineLight>(char const*);
createActorFunction<al::PrePassPointLight>(char const*);
createActorFunction<al::PrePassProjLight>(char const*);
createActorFunction<al::PrePassProjOrthoLight>(char const*);
createActorFunction<al::PrePassSpotLight>(char const*);
createActorFunction<ProjectRaceCheckPoint>(char const*);
createActorFunction<Pyramid>(char const*);
createActorFunction<QuestObj>(char const*);
createActorFunction<RabbitGraph>(char const*);
createActorFunction<RaceAudienceNpc>(char const*);
createActorFunction<RaceManGoal>(char const*);
createActorFunction<RaceManRace>(char const*);
createActorFunction<RaceManStart>(char const*);
createActorFunction<RaceWatcher>(char const*);
createActorFunction<RadiConRaceWatcher>(char const*);
createActorFunction<RadioCassette>(char const*);
createActorFunction<RadiconNpc>(char const*);
createActorFunction<Radish>(char const*);
createActorFunction<RailDrawer>(char const*);
createActorFunction<RankingNpc>(char const*);
createActorFunction<ReactionObjectCarBreakable>(char const*);
createActorFunction<ReflectBombGenerator>(char const*);
createActorFunction<RhythmSpotlight>(char const*);
createActorFunction<al::RippleGeneratePoint>(char const*);
createActorFunction<RotateTarget>(char const*);
createActorFunction<RouletteSwitch>(char const*);
createActorFunction<RouteGuideArrow>(char const*);
createActorFunction<RouteGuideRail>(char const*);
createActorFunction<RunAwayNpc>(char const*);
createActorFunction<SandGeyser>(char const*);
createActorFunction<SandWorldHomeLift>(char const*);
createActorFunction<SaucePan>(char const*);
createActorFunction<SaveFlagCheckObj>(char const*);
createActorFunction<ScenarioStartCamera>(char const*);
createActorFunction<Senobi>(char const*);
createActorFunction<SenobiGeneratePoint>(char const*);
createActorFunction<SenobiMoveMapParts>(char const*);
createActorFunction<SenobiMoveMapPartsConnector>(char const*);
createActorFunction<al::SeBarrierObj>(char const*);
createActorFunction<al::SePlayObj>(char const*);
createActorFunction<SePlayObjWithSave>(char const*);
createActorFunction<al::SePlayRail>(char const*);
createActorFunction<SequentialSwitch>(char const*);
createActorFunction<SessionBgmCtrlObj>(char const*);
createActorFunction<SessionMayorNpc>(char const*);
createActorFunction<SessionMusicianNpc>(char const*);
createActorFunction<Shibaken>(char const*);
createActorFunction<Shine>(char const*);
createActorFunction<ShineChipWatcher>(char const*);
createActorFunction<ShineFukankunWatchObj>(char const*);
createActorFunction<ShineTowerRocket>(char const*);
createActorFunction<ShopBgmPlayer>(char const*);
createActorFunction<ShopMark>(char const*);
createActorFunction<ShoppingWatcher>(char const*);
createActorFunction<SignBoardDanger>(char const*);
createActorFunction<SignBoardLayoutTexture>(char const*);
createActorFunction<SkyFukankunZoomCapMessage>(char const*);
createActorFunction<SkyWorldCloud>(char const*);
createActorFunction<SkyWorldKoopaFire>(char const*);
createActorFunction<SkyWorldKoopaFrame>(char const*);
createActorFunction<SkyWorldMiddleViewCloud>(char const*);
createActorFunction<SignBoard>(char const*);
createActorFunction<SnowWorldBigIcicle>(char const*);
createActorFunction<SnowWorldSequenceFlagCheckObj>(char const*);
createActorFunction<al::Sky>(char const*);
createActorFunction<SmallWanderBoss>(char const*);
createActorFunction<SneakingMan>(char const*);
createActorFunction<SnowManRaceNpc>(char const*);
createActorFunction<SnowVolume>(char const*);
createActorFunction<SnowVolumeEraser>(char const*);
createActorFunction<Souvenir>(char const*);
createActorFunction<SouvenirDirector>(char const*);
createActorFunction<Special2KeyMoveLift>(char const*);
createActorFunction<Special2KeyMoveParts>(char const*);
createActorFunction<SphinxQuiz>(char const*);
createActorFunction<SphinxRide>(char const*);
createActorFunction<SphinxTaxiWatcher>(char const*);
createActorFunction<Squirrel>(char const*);
createActorFunction<Stacker>(char const*);
createActorFunction<StackerCapWorldCtrl>(char const*);
createActorFunction<StageEventDemo>(char const*);
createActorFunction<StageSwitchSelector>(char const*);
createActorFunction<StageTalkDemoNpcCap>(char const*);
createActorFunction<Stake>(char const*);
createActorFunction<Statue>(char const*);
createActorFunction<StatueSnapMark>(char const*);
createActorFunction<SubActorLodFixPartsScenarioAction>(char const*);
createActorFunction<SwitchAnd>(char const*);
createActorFunction<al::SwitchKeyMoveMapParts>(char const*);
createActorFunction<CapMessagePlacement>(char const*);
createActorFunction<TalkMessageInfoPointSaveObj>(char const*);
createActorFunction<TalkNpc>(char const*);
createActorFunction<TalkNpcFreeze>(char const*);
createActorFunction<TalkPoint>(char const*);
createActorFunction<Tank>(char const*);
createActorFunction<TankReviveCtrl>(char const*);
createActorFunction<TaxiStop>(char const*);
createActorFunction<TextureReplaceScreen>(char const*);
createActorFunction<al::ThunderRenderRequester>(char const*);
createActorFunction<Togezo>(char const*);
createActorFunction<Togezo2D>(char const*);
createActorFunction<TokimekiMayorNpc>(char const*);
createActorFunction<TrampleBush>(char const*);
createActorFunction<TrampleSwitch>(char const*);
createActorFunction<TrampleSwitchTimer>(char const*);
createActorFunction<TransparentWall>(char const*);
createActorFunction<TreasureBox>(char const*);
createActorFunction<TreasureBoxKey>(char const*);
createActorFunction<TreasureBoxSequentialDirector>(char const*);
createActorFunction<TRex>(char const*);
createActorFunction<TRexScrollBreakMapParts>(char const*);
createActorFunction<Tsukkun>(char const*);
createActorFunction<TsukkunHole>(char const*);
createActorFunction<TwistChainList>(char const*);
createActorFunction<Utsubo>(char const*);
createActorFunction<UtsuboWatcher>(char const*);
createActorFunction<VocalMike>(char const*);
createActorFunction<VolleyballBase>(char const*);
createActorFunction<VolleyballNet>(char const*);
createActorFunction<VolleyballNpc>(char const*);
createActorFunction<Wanwan>(char const*);
createActorFunction<WanwanHole>(char const*);
createActorFunction<al::WaterAreaMoveModel>(char const*);
createActorFunction<WaterfallWorldBigBreakableWall>(char const*);
createActorFunction<WaterfallWorldFallDownBridge>(char const*);
createActorFunction<WaterfallWorldWaterfall>(char const*);
createActorFunction<WaterRoad>(char const*);
createActorFunction<WeightSwitch>(char const*);
createActorFunction<WheelWaveSurfParts>(char const*);
createActorFunction<WindBlowPuzzle>(char const*);
createActorFunction<WorldMapEarth>(char const*);
createActorFunction<WorldTravelingNpc>(char const*);
createActorFunction<WorldTravelingPeach>(char const*);
createActorFunction<WorldWarpHole>(char const*);
createActorFunction<Fastener>(char const*);
createActorFunction<FastenerObj>(char const*);
createActorFunction<al::AtmosScatterRequester>(char const*);
createActorFunction<al::BackHideParts>(char const*);
createActorFunction<CapRotateMapParts>(char const*);
createActorFunction<al::ClockMapParts>(char const*);
createActorFunction<al::ConveyerMapParts>(char const*);
createActorFunction<al::FallMapParts>(char const*);
createActorFunction<al::FloaterMapParts>(char const*);
createActorFunction<al::FlowMapParts>(char const*);
createActorFunction<al::GateMapParts>(char const*);
createActorFunction<al::KeyMoveMapParts>(char const*);
createActorFunction<al::KeyMoveMapPartsGenerator>(char const*);
createActorFunction<HackMapParts>(char const*);
createActorFunction<Pukupuku>(char const*);
createActorFunction<PulseSwitch>(char const*);
createActorFunction<RailCollision>(char const*);
createActorFunction<al::RailMoveMapParts>(char const*);
createActorFunction<RiseMapParts>(char const*);
createActorFunction<ReactionMapParts>(char const*);
createActorFunction<RiseMapPartsHolder>(char const*);
createActorFunction<RocketFlower>(char const*);
createActorFunction<al::RollingCubeMapParts>(char const*);
createActorFunction<al::RotateMapParts>(char const*);
createActorFunction<al::SeesawMapParts>(char const*);
createActorFunction<al::SlideMapParts>(char const*);
createActorFunction<al::SubActorLodMapParts>(char const*);
createActorFunction<al::SurfMapParts>(char const*);
createActorFunction<al::SwingMapParts>(char const*);
createActorFunction<al::SwitchDitherMapParts>(char const*);
createActorFunction<al::SwitchKeepOnWatcher>(char const*);
createActorFunction<al::SwitchOpenMapParts>(char const*);
createActorFunction<al::VisibleSwitchMapParts>(char const*);
createActorFunction<WaveSurfMapParts>(char const*);
createActorFunction<al::WheelMapParts>(char const*);
createActorFunction<al::WobbleMapParts>(char const*);
createActorFunction<WindBlowMapParts>(char const*);
createActorFunction<Yoshi>(char const*);
createActorFunction<YoshiFruit>(char const*);
createActorFunction<YoshiFruitShineHolder>(char const*);
createActorFunction<Yukimaru>(char const*);
createActorFunction<YukimaruRacer>(char const*);
createActorFunction<YukimaruRacerTiago>(char const*);
createActorFunction<AppearSwitchFixMapParts>(char const*);
createActorFunction<AppearSwitchFallMapParts>(char const*);
createAreaObjFunction<al::AreaObj>(char const*);
createAreaObjFunction<BirdGatheringSpotArea>(char const*);
createAreaObjFunction<al::CameraStartParamArea>(char const*);
createAreaObjFunction<ExtForceArea>(char const*);
createAreaObjFunction<ForceRecoveryKidsArea>(char const*);
createAreaObjFunction<NpcForceMaterialCodeArea>(char const*);
createAreaObjFunction<al::SePlayArea>(char const*);
createAreaObjFunction<al::SeBarrierArea>(char const*);
createAreaObjFunction<StainArea>(char const*);
createAreaObjFunction<al::TrafficArea>(char const*);
createAreaObjFunction<al::ViewCtrlArea>(char const*);
createAreaObjFunction<RouteGuideArea>(char const*);
createAreaObjFunction<MoveArea2D>(char const*);
createCameraPoserFunction<CameraPoserFollowLimit>(char const*);
createCameraPoserFunction<al::CameraPoserFix>(char const*);
createCameraPoserFunction<al::CameraPoserFixPoint>(char const*);
createCameraPoserFunction<al::CameraPoserRace>(char const*);
createCameraPoserFunction<al::CameraPoserRailMoveLookAt>(char const*);
createCameraPoserFunction<al::CameraPoserKinopioBrigade>(char const*);
createCameraPoserFunction<al::CameraPoserTalk>(char const*);
createCameraPoserFunction<al::CameraPoserRailMoveMovie>(char const*);
createCameraPoserFunction<al::CameraPoserBossBattle>(char const*);
createCameraPoserFunction<al::CameraPoserEntrance>(char const*);
createCameraPoserFunction<al::CameraPoserLookBoard>(char const*);
createCameraPoserFunction<al::CameraPoserLookDown>(char const*);
createCameraPoserFunction<al::CameraPoserSubjective>(char const*);
createCameraPoserFunction<al::CameraPoserTower>(char const*);
createCameraPoserFunction<al::KeyMoveCameraFix>(char const*);
createCameraPoserFunction<al::KeyMoveCameraRailMove>(char const*);
createCameraPoserFunction<al::KeyMoveCameraZoom>(char const*);
createCameraPoserFunction<ScenarioStartCameraPoserSimpleZoom>(char const*);
createCameraPoserFunction<ScenarioStartCameraPoserRailMove>(char const*);
createEventFlowNode<al::EventFlowNodeActionLoop>(char const*);
createEventFlowNode<al::EventFlowNodeActionOneTime>(char const*);
createEventFlowNode<al::EventFlowNodeActorBaseMovementEnd>(char const*);
createEventFlowNode<al::EventFlowNodeActorBaseMovementStart>(char const*);
createEventFlowNode<al::EventFlowNodeActorKill>(char const*);
createEventFlowNode<EventFlowNodeAmiiboTouchLayout>(char const*);
createEventFlowNode<al::EventFlowNodeAnimCameraStart>(char const*);
createEventFlowNode<EventFlowNodeAppearMapAmiiboHint>(char const*);
createEventFlowNode<EventFlowNodeBgmCtrl>(char const*);
createEventFlowNode<EventFlowNodeBindKeepDemoStart>(char const*);
createEventFlowNode<al::EventFlowNodeCameraEnd>(char const*);
createEventFlowNode<al::EventFlowNodeCameraStart>(char const*);
createEventFlowNode<EventFlowNodeCapMessage>(char const*);
createEventFlowNode<EventFlowNodeCapManHeroTalkSetDemoStartPose>(char const*);
createEventFlowNode<EventFlowNodeCapManHeroTalkAppear>(char const*);
createEventFlowNode<EventFlowNodeCapManHeroTalkFocus>(char const*);
createEventFlowNode<EventFlowNodeCapManHeroTalkPlayerTurn>(char const*);
createEventFlowNode<EventFlowNodeCapManHeroTalkReturn>(char const*);
createEventFlowNode<EventFlowNodeCapManHeroTalkSetDemoEndPose>(char const*);
createEventFlowNode<EventFlowNodeChangeStage>(char const*);
createEventFlowNode<EventFlowNodeChangeWorldDemoMessage>(char const*);
createEventFlowNode<EventFlowNodeCheckClear3CollectBgm>(char const*);
createEventFlowNode<EventFlowNodeCheckCompleteCollectBgm>(char const*);
createEventFlowNode<EventFlowNodeCheckCostume>(char const*);
createEventFlowNode<EventFlowNodeCheckCostumeInvisible>(char const*);
createEventFlowNode<EventFlowNodeCheckCostumeMissMatchPart>(char const*);
createEventFlowNode<EventFlowNodeCheckCostumePair>(char const*);
createEventFlowNode<EventFlowNodeCheckCount>(char const*);
createEventFlowNode<EventFlowNodeCheckFirstTalkCollectBgm>(char const*);
createEventFlowNode<EventFlowNodeCheckFlag>(char const*);
createEventFlowNode<EventFlowNodeCheckGetLinkShine>(char const*);
createEventFlowNode<EventFlowNodeCheckLifeUpItem>(char const*);
createEventFlowNode<EventFlowNodeCheckLink>(char const*);
createEventFlowNode<EventFlowNodeCheckMoonLockOpened>(char const*);
createEventFlowNode<EventFlowNodeCheckOpenDoorSnow>(char const*);
createEventFlowNode<EventFlowNodeCheckPlayingCollectBgm>(char const*);
createEventFlowNode<EventFlowNodeCheckPlayerOnGround>(char const*);
createEventFlowNode<EventFlowNodeCheckYukimaruRaceResult>(char const*);
createEventFlowNode<al::EventFlowNodeCheckSwitch>(char const*);
createEventFlowNode<al::EventFlowNodeCheckWaitSwitch>(char const*);
createEventFlowNode<EventFlowNodeCloseTalkMessage>(char const*);
createEventFlowNode<EventFlowNodeCoinPayment>(char const*);
createEventFlowNode<EventFlowNodeCutSceneDemoStart>(char const*);
createEventFlowNode<al::EventFlowNodeDemoAction>(char const*);
createEventFlowNode<al::EventFlowNodeDemoCamera>(char const*);
createEventFlowNode<EventFlowNodeDemoEnd>(char const*);
createEventFlowNode<EventFlowNodeDemoForceStartOnGround>(char const*);
createEventFlowNode<EventFlowNodeDemoForceStart>(char const*);
createEventFlowNode<al::EventFlowNodeDemoPlayerAction>(char const*);
createEventFlowNode<al::EventFlowNodeDemoPlayerHide>(char const*);
createEventFlowNode<al::EventFlowNodeDemoPlayerShow>(char const*);
createEventFlowNode<EventFlowNodeDemoResetPlayerDynamics>(char const*);
createEventFlowNode<EventFlowNodeDemoStart>(char const*);
createEventFlowNode<EventFlowNodeDirectGetLinkShine>(char const*);
createEventFlowNode<EventFlowNodeEnableHint>(char const*);
createEventFlowNode<al::EventFlowNodeEvent>(char const*);
createEventFlowNode<al::EventFlowNodeEventQuery>(char const*);
createEventFlowNode<EventFlowNodeFirstTalkEndCollectBgmNpc>(char const*);
createEventFlowNode<al::EventFlowNodeFork>(char const*);
createEventFlowNode<EventFlowNodeForcePutOnDemoCap>(char const*);
createEventFlowNode<EventFlowNodeGetAmiiboCostume>(char const*);
createEventFlowNode<EventFlowNodeGetAmiiboNotSearchHintNum>(char const*);
createEventFlowNode<EventFlowNodeGetCollectBgmBonus01>(char const*);
createEventFlowNode<EventFlowNodeGetCollectBgmBonus02>(char const*);
createEventFlowNode<EventFlowNodeGetSearchAmiibo>(char const*);
createEventFlowNode<al::EventFlowNodeHitReaction>(char const*);
createEventFlowNode<EventFlowNodeIsCostumeAmiibo>(char const*);
createEventFlowNode<EventFlowNodeIsEnableSearchAmiibo>(char const*);
createEventFlowNode<EventFlowNodeIsTalkAmiiboHelp>(char const*);
createEventFlowNode<EventFlowNodeKakkuTurn>(char const*);
createEventFlowNode<al::EventFlowNodeJoin>(char const*);
createEventFlowNode<al::EventFlowNodeJumpEntry>(char const*);
createEventFlowNode<EventFlowNodeMessageBalloon>(char const*);
createEventFlowNode<EventFlowNodeMessageTalk>(char const*);
createEventFlowNode<EventFlowNodeMessageTalkSpecialPurpose>(char const*);
createEventFlowNode<EventFlowNodeNextTalkMessage>(char const*);
createEventFlowNode<EventFlowNodeNormalDemoTryStart>(char const*);
createEventFlowNode<EventFlowNodeNpcMoveToLink>(char const*);
createEventFlowNode<EventFlowNodeOpenBgmList>(char const*);
createEventFlowNode<EventFlowNodePlayerAction>(char const*);
createEventFlowNode<EventFlowNodePlayerTurn>(char const*);
createEventFlowNode<EventFlowNodePopItem>(char const*);
createEventFlowNode<EventFlowNodePopLinkShine>(char const*);
createEventFlowNode<al::EventFlowNodeQueryJudge>(char const*);
createEventFlowNode<EventFlowNodeReplacePlayer>(char const*);
createEventFlowNode<EventFlowNodeSceneWipeClose>(char const*);
createEventFlowNode<EventFlowNodeSelectChoice>(char const*);
createEventFlowNode<EventFlowNodeSelectYesNo>(char const*);
createEventFlowNode<EventFlowNodeSessionWaitMusician>(char const*);
createEventFlowNode<EventFlowNodeSetDemoInfoDemoName>(char const*);
createEventFlowNode<al::EventFlowNodeSwitchOn>(char const*);
createEventFlowNode<al::EventFlowNodeSwitchOff>(char const*);
createEventFlowNode<al::EventFlowNodeTurnToPlayer>(char const*);
createEventFlowNode<al::EventFlowNodeTurnToPlayerActionOneTime>(char const*);
createEventFlowNode<al::EventFlowNodeTurnToPreDir>(char const*);
createEventFlowNode<EventFlowNodeUnlockHint>(char const*);
createEventFlowNode<EventFlowNodeWaitWipeOpenEnd>(char const*);
createEventFlowNode<EventFlowNodeWaitSimple>(char const*);
createEventFlowNode<EventFlowNodeWipeFadeBlackClose>(char const*);
createEventFlowNode<EventFlowNodeWipeFadeBlackOpen>(char const*);
createAreaShapeFunction<al::AreaShapeCubeBase>();
createAreaShapeFunction<al::AreaShapeCubeCenter>();
createAreaShapeFunction<al::AreaShapeCubeTop>();
createAreaShapeFunction<al::AreaShapeOval>();
createAreaShapeFunction<al::AreaShapeCylinderBase>();
createAreaShapeFunction<al::AreaShapeCylinderCenter>();
createAreaShapeFunction<al::AreaShapeCylinderTop>();
createAreaShapeFunction<al::AreaShapeInfinite>();
tryFindAudioInfo<al::AudioResourceLoadGroupInfo>(al::AudioInfoListWithParts<al::AudioResourceLoadGroupInfo> const*, char const*);
tryFindAudioInfo<al::AudioEffectInfo>(al::AudioInfoListWithParts<al::AudioEffectInfo> const*, char const*);
createAudioInfoList<al::AudioAddonSoundArchiveInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::AudioResourceLoadInfo>(al::ByamlIter const&, int);
tryFindAudioInfo<al::BgmSituationInfo>(al::AudioInfoListWithParts<al::BgmSituationInfo> const*, char const*);
tryFindAudioInfo<al::BgmMusicalInfo>(al::AudioInfoListWithParts<al::BgmMusicalInfo> const*, char const*);
tryFindAudioInfo<al::BgmResourceSuffixInfo>(al::AudioInfoListWithParts<al::BgmResourceSuffixInfo> const*, char const*);
tryFindAudioInfo<al::BgmResourceInfo>(al::AudioInfoListWithParts<al::BgmResourceInfo> const*, char const*);
tryFindAudioInfo<al::BgmResourceCategoryInfo>(al::AudioInfoListWithParts<al::BgmResourceCategoryInfo> const*, char const*);
tryFindAudioInfo<al::BgmEnableSituationInfo>(al::AudioInfoListWithParts<al::BgmEnableSituationInfo> const*, char const*);
createAudioInfoList<al::BgmCombinedLineInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmPlayInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmResourceCategoryInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmStageInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmStageInfo>(al::ByamlIter const&, al::ByamlIter const&, int, bool);
createAudioInfoList<al::BgmSituationInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmDemoSyncedProcInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmLineInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmResourceSuffixInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmEnableSituationInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmStartTriggerSituationInfo>(al::ByamlIter const&, int);
copyAudioInfoList<al::BgmResourceSuffixInfo>(al::AudioInfoListWithParts<al::BgmResourceSuffixInfo> const*, int);
copyAudioInfoList<al::BgmEnableSituationInfo>(al::AudioInfoListWithParts<al::BgmEnableSituationInfo> const*, int);
copyAudioInfoList<al::BgmStartTriggerSituationInfo>(al::AudioInfoListWithParts<al::BgmStartTriggerSituationInfo> const*, int);
createAudioInfoList<al::BgmStagePlayInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmStageScenarioInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmProcInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmRelationalSituationInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmSubSituationInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmDemoProcInfo>(al::ByamlIter const&, int);
copyAudioInfoList<al::BgmDemoProcInfo>(al::AudioInfoListWithParts<al::BgmDemoProcInfo> const*, int);
createAudioInfoList<al::BgmRhythmInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmChordInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmBpmInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmTimeSignatureInfo>(al::ByamlIter const&, int);
copyAudioInfoList<al::BgmRhythmInfo>(al::AudioInfoListWithParts<al::BgmRhythmInfo> const*, int);
copyAudioInfoList<al::BgmChordInfo>(al::AudioInfoListWithParts<al::BgmChordInfo> const*, int);
copyAudioInfoList<al::BgmBpmInfo>(al::AudioInfoListWithParts<al::BgmBpmInfo> const*, int);
copyAudioInfoList<al::BgmTimeSignatureInfo>(al::AudioInfoListWithParts<al::BgmTimeSignatureInfo> const*, int);
createCameraPoserFunction<al::CameraPoserParallelSimple>(char const*);
createCameraPoserFunction<al::CameraPoserFollowSimple>(char const*);
createCameraPoserFunction<al::CameraPoserQuickTurn>(char const*);
createAudioInfoList<al::SeResourceCategoryInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::SeDemoSyncedProcInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::SeSituationInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::SeActionInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::SePlayInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::SeEmitterInfo>(al::ByamlIter const&, int);
createAudioInfoListWithRedundantInfo<al::SeEmitterInfo>(al::ByamlIter const&, int, int, bool);
createAudioInfoList<al::SeHitReactionInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::SePlayInfoInAction>(al::ByamlIter const&, int);
copyAudioInfoList<al::SeResourceInfo>(al::AudioInfoListWithParts<al::SeResourceInfo> const*, int);
createAudioInfoList<al::SeResourceInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::SePlayInfoInHitReaction>(al::ByamlIter const&, int);
createAudioInfoList<al::SeMaterialInfo>(al::ByamlIter const&, int);
copyAudioInfoList<al::SeMaterialInfo>(al::AudioInfoListWithParts<al::SeMaterialInfo> const*, int);
tryFindAudioInfo<al::SeUserInfo>(al::AudioInfoListWithParts<al::SeUserInfo> const*, char const*);
tryFindAudioInfo<al::SePlayInfo>(al::AudioInfoListWithParts<al::SePlayInfo> const*, char const*);
tryFindAudioInfo<al::SeMaterialInfo>(al::AudioInfoListWithParts<al::SeMaterialInfo> const*, char const*);
createAudioInfoList<al::SeDemoProcInfo>(al::ByamlIter const&, int);
copyAudioInfoList<al::SeDemoProcInfo>(al::AudioInfoListWithParts<al::SeDemoProcInfo> const*, int);
createAudioInfoList<al::SeSituationCategoryInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::AudioBusSettingInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::AudioEffectInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::AudioEffectProcInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::AudioEachBusEffectInfo>(al::ByamlIter const&, int);
copyAudioInfoList<al::AudioEachBusEffectInfo>(al::AudioInfoListWithParts<al::AudioEachBusEffectInfo> const*, int);
copyAudioInfoList<al::AudioEffectProcInfo>(al::AudioInfoListWithParts<al::AudioEffectProcInfo> const*, int);
createAudioInfoList<al::AudioBusSendInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::AudioBusOutDeviceInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::AudioBusUserCategoryInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmPlayInfoInAction>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmActionInfo>(al::ByamlIter const&, int);
createAudioInfoList<al::BgmSourceInfo>(al::ByamlIter const&, int);

} } 
