#pragma once

class TimeBalloonDirector
{
public:
    TimeBalloonDirector();
    ~TimeBalloonDirector();
    init(al::ActorInitInfo const&, TimeBalloonNpc*, TimeBalloonSequenceInfo*, bool, bool, StageSceneLayout*);
    execute();
    startNotifier();
    endNotifier();
    exeStandby();
    isChangeNextStage(int*) const;
    getAccessor() const;
    getNoticeDirectorExecutor() const;
    getPlayerBalloonState(TimeBalloon::BalloonState*, int) const;
    requestDownload();
    getProfileDataHolder() const;
    isBalloonDataHolderOwnValid() const;
    getBalloonDataHolderOwn() const;
    isAchievementDataValid() const;
    getAchievementData() const;
    isExistAchievementData() const;
    getFindCoinMin() const;
    getFindCoinFirstPar() const;
    getFindCoinRetryPar() const;
    getDefaultSecFind() const;
    getDefaultSecPut() const;
    getPlayedCoinOnce() const;
    getPutBalloonCoinMax() const;
    getPlusTimeCoin() const;
    getTutorialBalloonCoin() const;
    getTotalCoinMax() const;
    getPlayedCoinMax() const;
    getFindCoinMax() const;
    getPlayedNumMax() const;
    getFindNumMax() const;
    getFindNumMaxMax() const;
    getFindCoinParam01() const;
    getFindCoinParam02() const;
    getFindCoinParam03() const;
    getFindCoinParam04() const;
    getFindCoinParam05() const;
    getFindNumParam01() const;
    getFindNumParam02() const;
    getFindNumParam03() const;
    getFindNumParam04() const;
    getFindNumParam05() const;
    getFindNumMaxParam01() const;
    getFindNumMaxParam02() const;
    getFindNumMaxParam03() const;
    getFindNumMaxParam04() const;
    getFindNumMaxParam05() const;
    getPlayedCoinParam01() const;
    getPlayedCoinParam02() const;
    getPlayedCoinParam03() const;
    getPlayedCoinParam04() const;
    getPlayedCoinParam05() const;
    getPlayedNumParam01() const;
    getPlayedNumParam02() const;
    getPlayedNumParam03() const;
    getPlayedNumParam04() const;
    getPlayedNumParam05() const;
    getPlayedNumMaxParam01() const;
    getPlayedNumMaxParam02() const;
    getPlayedNumMaxParam03() const;
    getPlayedNumMaxParam04() const;
    getPlayedNumMaxParam05() const;
    getNerveKeeper() const;
};
