#pragma once

namespace nn { namespace nex { 

class DataStoreProtocolClient
{
public:
    CallPrepareGetObject(nn::nex::ProtocolCallContext*, nn::nex::DataStorePrepareGetParam const&, nn::nex::DataStoreReqGetInfo*);
    CallPrepareGetObjectV1(nn::nex::ProtocolCallContext*, nn::nex::DataStorePrepareGetParamV1 const&, nn::nex::DataStoreReqGetInfoV1*);
    CallPrepareGetObjectOrMetaBinary(nn::nex::ProtocolCallContext*, nn::nex::DataStorePrepareGetParam const&, nn::nex::DataStoreReqGetInfo*, nn::nex::DataStoreReqGetAdditionalMeta*);
    CallPreparePostObject(nn::nex::ProtocolCallContext*, nn::nex::DataStorePreparePostParam const&, nn::nex::DataStoreReqPostInfo*);
    CallPreparePostObjectV1(nn::nex::ProtocolCallContext*, nn::nex::DataStorePreparePostParamV1 const&, nn::nex::DataStoreReqPostInfoV1*);
    CallCompletePostObject(nn::nex::ProtocolCallContext*, nn::nex::DataStoreCompletePostParam const&);
    CallCompletePostObjectV1(nn::nex::ProtocolCallContext*, nn::nex::DataStoreCompletePostParamV1 const&);
    CallCompletePostObjects(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&);
    CallPostMetaBinary(nn::nex::ProtocolCallContext*, nn::nex::DataStorePreparePostParam const&, unsigned long*);
    CallPostMetaBinaryWithDataId(nn::nex::ProtocolCallContext*, unsigned long const&, nn::nex::DataStorePreparePostParam const&);
    CallPostMetaBinariesWithDataId(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStorePreparePostParam> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    CallPrepareUpdateObject(nn::nex::ProtocolCallContext*, nn::nex::DataStorePrepareUpdateParam const&, nn::nex::DataStoreReqUpdateInfo*);
    CallCompleteUpdateObject(nn::nex::ProtocolCallContext*, nn::nex::DataStoreCompleteUpdateParam const&);
    CallDeleteObject(nn::nex::ProtocolCallContext*, nn::nex::DataStoreDeleteParam const&);
    CallDeleteObjects(nn::nex::ProtocolCallContext*, nn::nex::qVector<nn::nex::DataStoreDeleteParam> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    CallChangeMeta(nn::nex::ProtocolCallContext*, nn::nex::DataStoreChangeMetaParam const&);
    CallChangeMetaV1(nn::nex::ProtocolCallContext*, nn::nex::DataStoreChangeMetaParamV1 const&);
    CallChangeMetas(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStoreChangeMetaParam> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    CallChangeMetasV1(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStoreChangeMetaParamV1> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    CallGetMeta(nn::nex::ProtocolCallContext*, nn::nex::DataStoreGetMetaParam const&, nn::nex::DataStoreMetaInfo*);
    CallGetMetas(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&, nn::nex::DataStoreGetMetaParam const&, nn::nex::qVector<nn::nex::DataStoreMetaInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    CallGetMetasMultipleParam(nn::nex::ProtocolCallContext*, nn::nex::qVector<nn::nex::DataStoreGetMetaParam> const&, nn::nex::qVector<nn::nex::DataStoreMetaInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    CallSearchObject(nn::nex::ProtocolCallContext*, nn::nex::DataStoreSearchParam const&, nn::nex::DataStoreSearchResult*);
    CallSearchObjectLight(nn::nex::ProtocolCallContext*, nn::nex::DataStoreSearchParam const&, nn::nex::DataStoreSearchResult*);
    CallGetNotificationUrl(nn::nex::ProtocolCallContext*, nn::nex::DataStoreGetNotificationUrlParam const&, nn::nex::DataStoreReqGetNotificationUrlInfo*);
    CallGetNewArrivedNotifications(nn::nex::ProtocolCallContext*, nn::nex::DataStoreGetNewArrivedNotificationsParam const&, nn::nex::qVector<nn::nex::DataStoreNotification>*, bool*);
    CallGetNewArrivedNotificationsV1(nn::nex::ProtocolCallContext*, nn::nex::DataStoreGetNewArrivedNotificationsParam const&, nn::nex::qVector<nn::nex::DataStoreNotificationV1>*, bool*);
    CallRateObject(nn::nex::ProtocolCallContext*, nn::nex::DataStoreRatingTarget const&, nn::nex::DataStoreRateObjectParam const&, bool const&, nn::nex::DataStoreRatingInfo*);
    CallRateObjects(nn::nex::ProtocolCallContext*, nn::nex::qVector<nn::nex::DataStoreRatingTarget> const&, nn::nex::qVector<nn::nex::DataStoreRateObjectParam> const&, bool const&, bool const&, nn::nex::qVector<nn::nex::DataStoreRatingInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    CallRateObjectsWithPosting(nn::nex::ProtocolCallContext*, nn::nex::qVector<nn::nex::DataStoreRatingTarget> const&, nn::nex::qVector<nn::nex::DataStoreRateObjectParam> const&, nn::nex::qVector<nn::nex::DataStorePreparePostParam> const&, bool const&, bool const&, nn::nex::qVector<nn::nex::DataStoreRatingInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    CallRateObjectWithPosting(nn::nex::ProtocolCallContext*, nn::nex::DataStoreRatingTarget const&, nn::nex::DataStoreRateObjectParam const&, nn::nex::DataStorePreparePostParam const&, bool const&, nn::nex::DataStoreRatingInfo*);
    CallGetRating(nn::nex::ProtocolCallContext*, nn::nex::DataStoreRatingTarget const&, nn::nex::DataStoreRatingInfo*, unsigned long const&);
    CallGetRatings(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::qVector<nn::nex::DataStoreRatingInfoWithSlot> >*, nn::nex::qVector<nn::nex::qResult>*, unsigned long const&);
    CallResetRating(nn::nex::ProtocolCallContext*, nn::nex::DataStoreRatingTarget const&, unsigned long const&);
    CallResetRatings(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    CallGetSpecificMeta(nn::nex::ProtocolCallContext*, nn::nex::DataStoreGetSpecificMetaParam const&, nn::nex::qVector<nn::nex::DataStoreSpecificMetaInfo>*);
    CallGetSpecificMetaV1(nn::nex::ProtocolCallContext*, nn::nex::DataStoreGetSpecificMetaParamV1 const&, nn::nex::qVector<nn::nex::DataStoreSpecificMetaInfoV1>*);
    CallTouchObject(nn::nex::ProtocolCallContext*, nn::nex::DataStoreTouchObjectParam const&);
    CallGetRatingWithLog(nn::nex::ProtocolCallContext*, nn::nex::DataStoreRatingTarget const&, nn::nex::DataStoreRatingInfo*, nn::nex::DataStoreRatingLog*, unsigned long const&);
    CallGetPersistenceInfo(nn::nex::ProtocolCallContext*, unsigned long const&, unsigned short const&, nn::nex::DataStorePersistenceInfo*);
    CallGetPersistenceInfos(nn::nex::ProtocolCallContext*, unsigned long const&, nn::nex::qVector<unsigned short> const&, nn::nex::qVector<nn::nex::DataStorePersistenceInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    CallPerpetuateObject(nn::nex::ProtocolCallContext*, unsigned short const&, unsigned long const&, bool const&);
    CallUnperpetuateObject(nn::nex::ProtocolCallContext*, unsigned short const&, bool const&);
    CallGetPasswordInfo(nn::nex::ProtocolCallContext*, unsigned long const&, nn::nex::DataStorePasswordInfo*);
    CallGetPasswordInfos(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStorePasswordInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    CallGetObjectInfos(nn::nex::ProtocolCallContext*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStoreReqGetInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    CallAddToBufferQueue(nn::nex::ProtocolCallContext*, nn::nex::BufferQueueParam const&, nn::nex::qBuffer const&);
    CallAddToBufferQueues(nn::nex::ProtocolCallContext*, nn::nex::qVector<nn::nex::BufferQueueParam> const&, nn::nex::qVector<nn::nex::qBuffer> const&, nn::nex::qVector<nn::nex::qResult>*);
    CallGetBufferQueue(nn::nex::ProtocolCallContext*, nn::nex::BufferQueueParam const&, nn::nex::qVector<nn::nex::qBuffer>*);
    CallGetBufferQueues(nn::nex::ProtocolCallContext*, nn::nex::qVector<nn::nex::BufferQueueParam> const&, nn::nex::qVector<nn::nex::qVector<nn::nex::qBuffer> >*, nn::nex::qVector<nn::nex::qResult>*);
    CallClearBufferQueues(nn::nex::ProtocolCallContext*, nn::nex::qVector<nn::nex::BufferQueueParam> const&, nn::nex::qVector<nn::nex::qResult>*);
    CallSearchBalloon(nn::nex::ProtocolCallContext*, nn::nex::DataStoreSearchBalloonParam const&, nn::nex::qVector<nn::nex::DataStoreSearchBalloonResultSet>*);
    CallFetchMyInfos(nn::nex::ProtocolCallContext*, nn::nex::DataStoreFetchMyInfosParam const&, nn::nex::DataStoreFetchMyInfosResult*);
    PrepareGetObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStorePrepareGetParam const&, nn::nex::DataStoreReqGetInfo*);
    PrepareGetObjectV1_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStorePrepareGetParamV1 const&, nn::nex::DataStoreReqGetInfoV1*);
    PrepareGetObjectOrMetaBinary_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStorePrepareGetParam const&, nn::nex::DataStoreReqGetInfo*, nn::nex::DataStoreReqGetAdditionalMeta*);
    PreparePostObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStorePreparePostParam const&, nn::nex::DataStoreReqPostInfo*);
    PreparePostObjectV1_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStorePreparePostParamV1 const&, nn::nex::DataStoreReqPostInfoV1*);
    CompletePostObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreCompletePostParam const&);
    CompletePostObjectV1_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreCompletePostParamV1 const&);
    CompletePostObjects_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&);
    PostMetaBinary_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStorePreparePostParam const&, unsigned long*);
    PostMetaBinaryWithDataId_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, unsigned long const&, nn::nex::DataStorePreparePostParam const&);
    PostMetaBinariesWithDataId_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStorePreparePostParam> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    PrepareUpdateObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStorePrepareUpdateParam const&, nn::nex::DataStoreReqUpdateInfo*);
    CompleteUpdateObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreCompleteUpdateParam const&);
    DeleteObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreDeleteParam const&);
    ChangeMeta_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreChangeMetaParam const&);
    GetMeta_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreGetMetaParam const&, nn::nex::DataStoreMetaInfo*);
    GetMetas_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&, nn::nex::DataStoreGetMetaParam const&, nn::nex::qVector<nn::nex::DataStoreMetaInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    GetMetasMultipleParam_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<nn::nex::DataStoreGetMetaParam> const&, nn::nex::qVector<nn::nex::DataStoreMetaInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    SearchObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreSearchParam const&, nn::nex::DataStoreSearchResult*);
    SearchObjectLight_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreSearchParam const&, nn::nex::DataStoreSearchResult*);
    GetNotificationUrl_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreGetNotificationUrlParam const&, nn::nex::DataStoreReqGetNotificationUrlInfo*);
    GetNewArrivedNotifications_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreGetNewArrivedNotificationsParam const&, nn::nex::qVector<nn::nex::DataStoreNotification>*, bool*);
    GetNewArrivedNotificationsV1_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreGetNewArrivedNotificationsParam const&, nn::nex::qVector<nn::nex::DataStoreNotificationV1>*, bool*);
    RateObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreRatingTarget const&, nn::nex::DataStoreRateObjectParam const&, bool const&, nn::nex::DataStoreRatingInfo*);
    GetRating_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreRatingTarget const&, nn::nex::DataStoreRatingInfo*, unsigned long const&);
    GetRatings_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::qVector<nn::nex::DataStoreRatingInfoWithSlot> >*, nn::nex::qVector<nn::nex::qResult>*, unsigned long const&);
    GetSpecificMeta_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreGetSpecificMetaParam const&, nn::nex::qVector<nn::nex::DataStoreSpecificMetaInfo>*);
    GetSpecificMetaV1_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreGetSpecificMetaParamV1 const&, nn::nex::qVector<nn::nex::DataStoreSpecificMetaInfoV1>*);
    ResetRating_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreRatingTarget const&, unsigned long const&);
    ResetRatings_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    TouchObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreTouchObjectParam const&);
    GetRatingWithLog_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreRatingTarget const&, nn::nex::DataStoreRatingInfo*, nn::nex::DataStoreRatingLog*, unsigned long const&);
    GetPersistenceInfo_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, unsigned long const&, unsigned short const&, nn::nex::DataStorePersistenceInfo*);
    GetPersistenceInfos_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, unsigned long const&, nn::nex::qVector<unsigned short> const&, nn::nex::qVector<nn::nex::DataStorePersistenceInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    PerpetuateObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, unsigned short const&, unsigned long const&, bool const&);
    UnperpetuateObject_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, unsigned short const&, bool const&);
    GetPasswordInfo_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, unsigned long const&, nn::nex::DataStorePasswordInfo*);
    GetPasswordInfos_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStorePasswordInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    GetObjectInfos_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStoreReqGetInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    DataStoreProtocolClient(unsigned short);
    ProtoReturn_PrepareGetObjectV1(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PreparePostObjectV1(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_CompletePostObjectV1(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_DeleteObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    DeleteObjects_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<nn::nex::DataStoreDeleteParam> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    ProtoReturn_DeleteObjects(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ChangeMetaV1_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreChangeMetaParamV1 const&);
    ProtoReturn_ChangeMetaV1(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ChangeMetasV1_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStoreChangeMetaParamV1> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    ProtoReturn_ChangeMetasV1(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetMeta(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetMetas(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PrepareUpdateObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_CompleteUpdateObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_SearchObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetNotificationUrl(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetNewArrivedNotificationsV1(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_RateObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetRating(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetRatings(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_ResetRating(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_ResetRatings(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetSpecificMetaV1(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PostMetaBinary(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_TouchObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetRatingWithLog(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PreparePostObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PrepareGetObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_CompletePostObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetNewArrivedNotifications(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetSpecificMeta(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetPersistenceInfo(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetPersistenceInfos(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PerpetuateObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_UnperpetuateObject(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PrepareGetObjectOrMetaBinary(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetPasswordInfo(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetPasswordInfos(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetMetasMultipleParam(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_CompletePostObjects(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_ChangeMeta(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ChangeMetas_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<unsigned long> const&, nn::nex::qVector<nn::nex::DataStoreChangeMetaParam> const&, bool const&, nn::nex::qVector<nn::nex::qResult>*);
    ProtoReturn_ChangeMetas(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    RateObjects_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<nn::nex::DataStoreRatingTarget> const&, nn::nex::qVector<nn::nex::DataStoreRateObjectParam> const&, bool const&, bool const&, nn::nex::qVector<nn::nex::DataStoreRatingInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    ProtoReturn_RateObjects(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PostMetaBinaryWithDataId(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_PostMetaBinariesWithDataId(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    RateObjectWithPosting_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreRatingTarget const&, nn::nex::DataStoreRateObjectParam const&, nn::nex::DataStorePreparePostParam const&, bool const&, nn::nex::DataStoreRatingInfo*);
    ProtoReturn_RateObjectWithPosting(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    RateObjectsWithPosting_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<nn::nex::DataStoreRatingTarget> const&, nn::nex::qVector<nn::nex::DataStoreRateObjectParam> const&, nn::nex::qVector<nn::nex::DataStorePreparePostParam> const&, bool const&, bool const&, nn::nex::qVector<nn::nex::DataStoreRatingInfo>*, nn::nex::qVector<nn::nex::qResult>*);
    ProtoReturn_RateObjectsWithPosting(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_GetObjectInfos(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ProtoReturn_SearchObjectLight(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    AddToBufferQueue_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::BufferQueueParam const&, nn::nex::qBuffer const&);
    ProtoReturn_AddToBufferQueue(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    AddToBufferQueues_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<nn::nex::BufferQueueParam> const&, nn::nex::qVector<nn::nex::qBuffer> const&, nn::nex::qVector<nn::nex::qResult>*);
    ProtoReturn_AddToBufferQueues(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    GetBufferQueue_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::BufferQueueParam const&, nn::nex::qVector<nn::nex::qBuffer>*);
    ProtoReturn_GetBufferQueue(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    GetBufferQueues_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<nn::nex::BufferQueueParam> const&, nn::nex::qVector<nn::nex::qVector<nn::nex::qBuffer> >*, nn::nex::qVector<nn::nex::qResult>*);
    ProtoReturn_GetBufferQueues(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ClearBufferQueues_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::qVector<nn::nex::BufferQueueParam> const&, nn::nex::qVector<nn::nex::qResult>*);
    ProtoReturn_ClearBufferQueues(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    SearchBalloon_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreSearchBalloonParam const&, nn::nex::qVector<nn::nex::DataStoreSearchBalloonResultSet>*);
    ProtoReturn_SearchBalloon(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    FetchMyInfos_PrepareRequest(nn::nex::ProtocolCallContext*, nn::nex::Message*, nn::nex::DataStoreFetchMyInfosParam const&, nn::nex::DataStoreFetchMyInfosResult*);
    ProtoReturn_FetchMyInfos(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ExtractCallSpecificResults(nn::nex::Message*, nn::nex::ProtocolCallContext*);
    ~DataStoreProtocolClient();
    CreateResponder() const;
    s_protoReturnFunctions;
};

} } 
