#pragma once

namespace std { namespace __1 {

__tree_balance_after_insert<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*);
__sort<std::__1::__less<nn::nex::PacketBufferManager::UnitHeapParam, nn::nex::PacketBufferManager::UnitHeapParam>&, nn::nex::PacketBufferManager::UnitHeapParam*>(nn::nex::PacketBufferManager::UnitHeapParam*, nn::nex::PacketBufferManager::UnitHeapParam*, std::__1::__less<nn::nex::PacketBufferManager::UnitHeapParam, nn::nex::PacketBufferManager::UnitHeapParam>&);
__sort4<std::__1::__less<nn::nex::PacketBufferManager::UnitHeapParam, nn::nex::PacketBufferManager::UnitHeapParam>&, nn::nex::PacketBufferManager::UnitHeapParam*>(nn::nex::PacketBufferManager::UnitHeapParam*, nn::nex::PacketBufferManager::UnitHeapParam*, nn::nex::PacketBufferManager::UnitHeapParam*, nn::nex::PacketBufferManager::UnitHeapParam*, std::__1::__less<nn::nex::PacketBufferManager::UnitHeapParam, nn::nex::PacketBufferManager::UnitHeapParam>&);
__insertion_sort_incomplete<std::__1::__less<nn::nex::PacketBufferManager::UnitHeapParam, nn::nex::PacketBufferManager::UnitHeapParam>&, nn::nex::PacketBufferManager::UnitHeapParam*>(nn::nex::PacketBufferManager::UnitHeapParam*, nn::nex::PacketBufferManager::UnitHeapParam*, std::__1::__less<nn::nex::PacketBufferManager::UnitHeapParam, nn::nex::PacketBufferManager::UnitHeapParam>&);
__tree_remove<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*);
__sort<bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&), alCollisionUtil::SphereMoveHitInfo*>(alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&));
__sort3<bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&), alCollisionUtil::SphereMoveHitInfo*>(alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&));
__sort4<bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&), alCollisionUtil::SphereMoveHitInfo*>(alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&));
__sort5<bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&), alCollisionUtil::SphereMoveHitInfo*>(alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&));
__insertion_sort_3<bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&), alCollisionUtil::SphereMoveHitInfo*>(alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&));
__insertion_sort_incomplete<bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&), alCollisionUtil::SphereMoveHitInfo*>(alCollisionUtil::SphereMoveHitInfo*, alCollisionUtil::SphereMoveHitInfo*, bool (*&)(alCollisionUtil::SphereMoveHitInfo const&, alCollisionUtil::SphereMoveHitInfo const&));
__sort<al::SensorSortCmpFunc&, al::HitSensor**>(al::HitSensor**, al::HitSensor**, al::SensorSortCmpFunc&);
__sort3<al::SensorSortCmpFunc&, al::HitSensor**>(al::HitSensor**, al::HitSensor**, al::HitSensor**, al::SensorSortCmpFunc&);
__sort5<al::SensorSortCmpFunc&, al::HitSensor**>(al::HitSensor**, al::HitSensor**, al::HitSensor**, al::HitSensor**, al::HitSensor**, al::SensorSortCmpFunc&);
__insertion_sort_incomplete<al::SensorSortCmpFunc&, al::HitSensor**>(al::HitSensor**, al::HitSensor**, al::SensorSortCmpFunc&);
__sort<nn::vfx::detail::SortCompareLessUInt<nn::vfx::System::SortEmitterSetData>&, nn::vfx::System::SortEmitterSetData*>(nn::vfx::System::SortEmitterSetData*, nn::vfx::System::SortEmitterSetData*, nn::vfx::detail::SortCompareLessUInt<nn::vfx::System::SortEmitterSetData>&);
__sort4<nn::vfx::detail::SortCompareLessUInt<nn::vfx::System::SortEmitterSetData>&, nn::vfx::System::SortEmitterSetData*>(nn::vfx::System::SortEmitterSetData*, nn::vfx::System::SortEmitterSetData*, nn::vfx::System::SortEmitterSetData*, nn::vfx::System::SortEmitterSetData*, nn::vfx::detail::SortCompareLessUInt<nn::vfx::System::SortEmitterSetData>&);
__insertion_sort_incomplete<nn::vfx::detail::SortCompareLessUInt<nn::vfx::System::SortEmitterSetData>&, nn::vfx::System::SortEmitterSetData*>(nn::vfx::System::SortEmitterSetData*, nn::vfx::System::SortEmitterSetData*, nn::vfx::detail::SortCompareLessUInt<nn::vfx::System::SortEmitterSetData>&);
__sort<nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&);
__sort4<nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&);
__sort5<nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&);
__insertion_sort_3<nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&);
__insertion_sort_incomplete<nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareGreaterIndexStable<nn::vfx::detail::SortData>&);
__sort<nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&);
__sort4<nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&);
__sort5<nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&);
__insertion_sort_3<nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&);
__insertion_sort_incomplete<nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareLessIndexStable<nn::vfx::detail::SortData>&);
__sort<nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&);
__sort4<nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&);
__sort5<nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&);
__insertion_sort_3<nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&);
__insertion_sort_incomplete<nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewInvZ<nn::vfx::detail::SortData>&);
__sort<nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&);
__sort4<nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&);
__sort5<nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&);
__insertion_sort_3<nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&);
__insertion_sort_incomplete<nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&, nn::vfx::detail::SortData*>(nn::vfx::detail::SortData*, nn::vfx::detail::SortData*, nn::vfx::detail::SortCompareViewZ<nn::vfx::detail::SortData>&);

} } 
